global using Common;
global using AutoMapper;
global using FluentValidation;
global using Microsoft.AspNetCore.Mvc;
global using Nationalities.Shared;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;